---
- name: install mcserver

  hosts: localhost
  tasks:

  - name: Update apt package manager repositories cache
    become: true
    apt:
     update_cache: yes

  - name: Install Java using Ansible
    become: yes
    apt:
     name: "{{ packages }}"
     state: present
    vars:
     packages:
     - openjdk-8-jdk

  - name: Create MCServer directory
    file:
     path: /opt/minecraft
     state: directory

  - name: Download Installer Forge Server 1.12.2
    get_url:
     url: https://maven.minecraftforge.net/net/minecraftforge/forge/1.12.2-14.23.5.2860/forge-1.12.2-14.23.5.2860-installer.jar
     dest: /opt/minecraft

  - name: Install Forge Server 1.12.2
    raw: cd /opt/minecraft && sudo java -jar /opt/minecraft/forge-1.12.2-14.23.5.2860-installer.jar --installServer

  - name: First Start Forge Server 1.12.2
    raw: cd /opt/minecraft && java -Xms1024M -Xmx2000M -jar /opt/minecraft/forge-1.12.2-14.23.5.2860.jar nogui

  - name: Accept EULA
    lineinfile:
     path: /opt/minecraft/eula.txt
     regexp: 'eula'
     line: eula=true

  - name: Download Mods
    get_url:
     url: "{{ item }}"
     dest: /opt/minecraft/mods
    loop:
     - https://media.forgecdn.net/files/3078/604/industrialcraft-2-2.8.221-ex112.jar
     - https://media.forgecdn.net/files/3204/475/buildcraft-all-7.99.24.8.jar
     - https://media.forgecdn.net/files/2615/327/additionalpipes-6.0.0.8.jar
     - https://media.forgecdn.net/files/2667/2/Advanced+Machines-61.0.1.jar
     - https://media.forgecdn.net/files/3034/109/advmachinespatch-1.0.jar
     - https://media.forgecdn.net/files/3401/706/AdvSolarPatch-1.2.1.jar
     - https://media.forgecdn.net/files/2652/182/Advanced+Solar+Panels-4.3.0.jar
     - https://media.forgecdn.net/files/2518/31/bdlib-1.14.3.12-mc1.12.2.jar
     - https://media.forgecdn.net/files/2606/285/Bookshelf-1.12.2-2.3.557.jar
     - https://media.forgecdn.net/files/2633/646/CompactSolars-1.12.2-5.0.18.341-universal.jar
     - https://media.forgecdn.net/files/2664/227/EnchantingPlus-1.12.2-5.0.176.jar
     - https://media.forgecdn.net/files/2992/813/energyconverters_1.12.2-1.3.7.30.jar
     - https://media.forgecdn.net/files/2918/418/forestry_1.12.2-5.8.2.422.jar
     - https://media.forgecdn.net/files/2516/219/generators-0.9.20.12-mc1.12.2.jar
     - https://media.forgecdn.net/files/2974/106/ImmersiveEngineering-0.12-98.jar
     - https://media.forgecdn.net/files/2747/935/ironchest-1.12.2-7.0.72.847.jar
     - https://media.forgecdn.net/files/3040/523/jei_1.12.2-4.16.1.301.jar
     - https://media.forgecdn.net/files/2916/2/journeymap-1.12.2-5.7.1.jar
     - https://media.forgecdn.net/files/2671/230/NoMoreRecipeConflict-0.13(1.12.2).jar
     - https://media.forgecdn.net/files/2687/757/railcraft-12.0.0.jar

  - name: Second Start Forge Server 1.12.2
    raw: cd /opt/minecraft && sudo screen -dm -S minecraft java -Xms1024M -Xmx2000M -jar /opt/minecraft/forge-1.12.2-14.23.5.2860.jar nogui

  - name: Stop Forge Server 1.12.2
    raw: sudo screen -S minecraft -p 0 -X stuff "stop^M"

  - name: Wait until server.properties creating
    wait_for:
     timeout: 180

  - name: Config server.properties
    become: yes
    lineinfile:
     path: /opt/minecraft/server.properties
     regexp: 'online-mode'
     line: online-mode=false

  - name: Create start script
    lineinfile:
     path: /opt/minecraft/start.sh
     create: yes
     line:
      cd /opt/minecraft && sudo screen -dm -S minecraft java -Xms1024M -Xmx2000M -jar /opt/minecraft/forge-1.12.2-14.23.5.2860.jar nogui
     mode: 0755
 
  - name: start script
    shell: cd /opt/minecraft/ && sudo ./start.sh

  - name: create rc.local
    shell: echo "#!/bin/sh" > /etc/rc.local

  - name: config rc.local
    blockinfile:
     path: /etc/rc.local
     block: |
      /opt/minecraft/start.sh
      exit 0
     mode: 0755
